ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Call" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."CallAnalysis" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."CallStage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Objection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."OrgSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Playbook" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."AuditLog" ENABLE ROW LEVEL SECURITY;
